module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '😘', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💗'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/L21wT8us3gf8DS4fqbOIAy?mode=ems_copy_c👈?mode=ac_t',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/secl9d.jpg',
    NEWSLETTER_JID: '120363404570861723@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '*NEDIYA MD* ',
    OWNER_NAME: '𝚗𝚎𝚍𝚒𝚢𝚊',
    OWNER_NUMBER: '94715734793',
    BOT_VERSION: '1.1.1',
    BOT_FOOTER: '> ©NEDIYA BOY',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb2l7408vd1GSo8n3a19',
};
